//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The account is not active..
        /// </summary>
        public static string AccountInActive {
            get {
                return ResourceManager.GetString("AccountInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account locked due to excessive login failures..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account locked due to excessive login failures..
        /// </summary>
        public static string AccountLocked1 {
            get {
                return ResourceManager.GetString("AccountLocked1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account locked. Please contact your administrator..
        /// </summary>
        public static string AccountLockedByAdmin {
            get {
                return ResourceManager.GetString("AccountLockedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account locked. Please contact your administrator..
        /// </summary>
        public static string AccountLockedByAdmin1 {
            get {
                return ResourceManager.GetString("AccountLockedByAdmin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Api key &apos;{0}&apos; failed to authenticate. Key has expired..
        /// </summary>
        public static string ApiKeyExpired {
            get {
                return ResourceManager.GetString("ApiKeyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid api key..
        /// </summary>
        public static string ApiKeyInvalid {
            get {
                return ResourceManager.GetString("ApiKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Api key &apos;{0}&apos; failed to authenticate. Key is not active..
        /// </summary>
        public static string ApiKeyNotActive {
            get {
                return ResourceManager.GetString("ApiKeyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Api key &apos;{0}&apos; failed to authenticate. Key was not found..
        /// </summary>
        public static string ApiKeyNotFound {
            get {
                return ResourceManager.GetString("ApiKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Api key &apos;{0}&apos; failed to authenticate. Failed to parse api key guid..
        /// </summary>
        public static string ApiKeyParseFailed {
            get {
                return ResourceManager.GetString("ApiKeyParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The application id is invalid..
        /// </summary>
        public static string AppIdInvalid {
            get {
                return ResourceManager.GetString("AppIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The application id is invalid..
        /// </summary>
        public static string AppIdInvalid1 {
            get {
                return ResourceManager.GetString("AppIdInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The application specific user id was not provided..
        /// </summary>
        public static string AppUserIdNotProvided {
            get {
                return ResourceManager.GetString("AppUserIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A &apos;{0}&apos; argument is required..
        /// </summary>
        public static string ARequired {
            get {
                return ResourceManager.GetString("ARequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Authentication failed..
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error loading authentication manager..
        /// </summary>
        public static string AuthManagerLoadError {
            get {
                return ResourceManager.GetString("AuthManagerLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Bing Maps api key was not found in the configuration file..
        /// </summary>
        public static string BingMapsKeyNotFound {
            get {
                return ResourceManager.GetString("BingMapsKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Bing Maps URL was not found in the configuration file..
        /// </summary>
        public static string BingMapsUrlNotFound {
            get {
                return ResourceManager.GetString("BingMapsUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot read the token..
        /// </summary>
        public static string CannotReadToken {
            get {
                return ResourceManager.GetString("CannotReadToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The client application cannot be verified..
        /// </summary>
        public static string ClientAppUnverified {
            get {
                return ResourceManager.GetString("ClientAppUnverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; connection string was not found in the configuration file..
        /// </summary>
        public static string ConnectionStringNotFoundInConfig {
            get {
                return ResourceManager.GetString("ConnectionStringNotFoundInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The container &apos;{0}&apos; does not exist..
        /// </summary>
        public static string ContainerDoesNotExist {
            get {
                return ResourceManager.GetString("ContainerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content already exists for &apos;{0}&apos;..
        /// </summary>
        public static string ContentAlreadyExists {
            get {
                return ResourceManager.GetString("ContentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content not found for &apos;{0}&apos;..
        /// </summary>
        public static string ContentNotFound {
            get {
                return ResourceManager.GetString("ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A data exception occurred..
        /// </summary>
        public static string DataException {
            get {
                return ResourceManager.GetString("DataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The date is invalid..
        /// </summary>
        public static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The nna-date header is missing, or the date is invalid..
        /// </summary>
        public static string DateMissingOrInvalid {
            get {
                return ResourceManager.GetString("DateMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The attribute is not allowed to be deleted..
        /// </summary>
        public static string DeleteOptionNotAllowed {
            get {
                return ResourceManager.GetString("DeleteOptionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Encrypted text is required..
        /// </summary>
        public static string EncryptedTextRequired {
            get {
                return ResourceManager.GetString("EncryptedTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Encrypted text is required..
        /// </summary>
        public static string EncryptedTextRequired1 {
            get {
                return ResourceManager.GetString("EncryptedTextRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An encryption key is required..
        /// </summary>
        public static string EncryptionKeyRequired {
            get {
                return ResourceManager.GetString("EncryptionKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An encryption key is required..
        /// </summary>
        public static string EncryptionKeyRequired1 {
            get {
                return ResourceManager.GetString("EncryptionKeyRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geocoding failed. Confidence was &apos;{0}&apos;..
        /// </summary>
        public static string GeoCodeFailedConfidence {
            get {
                return ResourceManager.GetString("GeoCodeFailedConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geocoding failed. The coordinates were not found or not valid..
        /// </summary>
        public static string GeoCodeFailedCoordinatesNotFound {
            get {
                return ResourceManager.GetString("GeoCodeFailedCoordinatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geocoding failed. The entity type found was not an address..
        /// </summary>
        public static string GeoCodeFailedEntityType {
            get {
                return ResourceManager.GetString("GeoCodeFailedEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geocoding failed. The entity type found was not a postal code..
        /// </summary>
        public static string GeoCodeFailedEntityTypeZip {
            get {
                return ResourceManager.GetString("GeoCodeFailedEntityTypeZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geocoding failed. The match code must be &apos;Good&apos;..
        /// </summary>
        public static string GeoCodeFailedMatchCode {
            get {
                return ResourceManager.GetString("GeoCodeFailedMatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input is required..
        /// </summary>
        public static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input is required..
        /// </summary>
        public static string InputRequired1 {
            get {
                return ResourceManager.GetString("InputRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input text is required..
        /// </summary>
        public static string InputTextRequired {
            get {
                return ResourceManager.GetString("InputTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input text is required..
        /// </summary>
        public static string InputTextRequired1 {
            get {
                return ResourceManager.GetString("InputTextRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid data..
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid data..
        /// </summary>
        public static string InvalidData1 {
            get {
                return ResourceManager.GetString("InvalidData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid policy document..
        /// </summary>
        public static string InvalidPolicyDoc {
            get {
                return ResourceManager.GetString("InvalidPolicyDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Policy format..
        /// </summary>
        public static string InvalidPolicyFormat {
            get {
                return ResourceManager.GetString("InvalidPolicyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid or missing authentication token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid username or passcode..
        /// </summary>
        public static string InvalidUsernamePasscode {
            get {
                return ResourceManager.GetString("InvalidUsernamePasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid username or passcode..
        /// </summary>
        public static string InvalidUsernamePasscode1 {
            get {
                return ResourceManager.GetString("InvalidUsernamePasscode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid username/password pair..
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid username/password pair..
        /// </summary>
        public static string InvalidUsernamePassword1 {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An initialization vector is required..
        /// </summary>
        public static string IVRequired {
            get {
                return ResourceManager.GetString("IVRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An initialization vector is required..
        /// </summary>
        public static string IVRequired1 {
            get {
                return ResourceManager.GetString("IVRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid key signature..
        /// </summary>
        public static string KeySignatureInvalid {
            get {
                return ResourceManager.GetString("KeySignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can only convert an instance of enum..
        /// </summary>
        public static string OnlyConvertToEnum {
            get {
                return ResourceManager.GetString("OnlyConvertToEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can only convert to a string..
        /// </summary>
        public static string OnlyConvertToString {
            get {
                return ResourceManager.GetString("OnlyConvertToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The organization id is invalid..
        /// </summary>
        public static string OrgIdInvalid {
            get {
                return ResourceManager.GetString("OrgIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The organization id is invalid..
        /// </summary>
        public static string OrgIdInvalid1 {
            get {
                return ResourceManager.GetString("OrgIdInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PartitionKey is reserved..
        /// </summary>
        public static string PartitionKeyReserved {
            get {
                return ResourceManager.GetString("PartitionKeyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The passcode has expired..
        /// </summary>
        public static string PasscodeExpired {
            get {
                return ResourceManager.GetString("PasscodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The passcode has expired..
        /// </summary>
        public static string PasscodeExpired1 {
            get {
                return ResourceManager.GetString("PasscodeExpired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password expired..
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password expired..
        /// </summary>
        public static string PasswordExpired1 {
            get {
                return ResourceManager.GetString("PasswordExpired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RowKey is reserved..
        /// </summary>
        public static string RowKeyReserved {
            get {
                return ResourceManager.GetString("RowKeyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; application setting was not found in the configuration file..
        /// </summary>
        public static string SettingNotFoundInConfig {
            get {
                return ResourceManager.GetString("SettingNotFoundInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Signature does not match..
        /// </summary>
        public static string SignatureNotMatch {
            get {
                return ResourceManager.GetString("SignatureNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Storage connection string name not found in the configuration..
        /// </summary>
        public static string StorageConnectStringNotFound {
            get {
                return ResourceManager.GetString("StorageConnectStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Timestamp is reserved..
        /// </summary>
        public static string TimestampReserved {
            get {
                return ResourceManager.GetString("TimestampReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The token has expired..
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The security token must be issued by a participating identity provider..
        /// </summary>
        public static string TokenIssuedByParticipatingIP {
            get {
                return ResourceManager.GetString("TokenIssuedByParticipatingIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Universal scope is required..
        /// </summary>
        public static string UniversalScopeRequired {
            get {
                return ResourceManager.GetString("UniversalScopeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The attribute is associated to a product and is not allowed to be updated..
        /// </summary>
        public static string UpdateOptionNotAllowed {
            get {
                return ResourceManager.GetString("UpdateOptionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The upload failed..
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The user id is invalid..
        /// </summary>
        public static string UserIdInvalid {
            get {
                return ResourceManager.GetString("UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The user id is invalid..
        /// </summary>
        public static string UserIdInvalid1 {
            get {
                return ResourceManager.GetString("UserIdInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The attribute may only decorate methods in a Web Api controller..
        /// </summary>
        public static string WebApiAttributeOnly {
            get {
                return ResourceManager.GetString("WebApiAttributeOnly", resourceCulture);
            }
        }
    }
}
