






//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Security
{
	/// <summary>
	/// Provides an enumerated list of scopes.
	/// </summary>
	public enum Scope
	{
		/// <summary>
		/// The scope is unknown.
		/// </summary>
		Unknown,
	}
}

