//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Common.Security
{
	/// <summary>
	/// Provides an enumerated list of user types.
	/// </summary>
    public enum UserType
    {
		/// <summary>
		/// The user type is unknown.
		/// </summary>
		Unknown = 0,

		/// <summary>
		/// An automated application.
		/// </summary>
        Application = 1,

		/// <summary>
		/// A person.
		/// </summary>
        Person = 2,

		/// <summary>
		/// An application publisher.
		/// </summary>
        Publisher = 3,

	}
}